/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    events: Event;
    clients: Client;
    jobs: Job;
    organizations: Organization;
    'intake-events': IntakeEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    clients: {
      jobs: 'jobs';
    };
    organizations: {
      events: 'events';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    'intake-events': IntakeEventsSelect<false> | IntakeEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Auto-generated from filename. Edit if needed.
   */
  alt: string;
  /**
   * Auto-tagged: PNG files get 'drawing', video files get 'video'.
   */
  tags?: ('portrait' | 'outtake' | 'promo' | 'client' | 'video' | 'drawing')[] | null;
  /**
   * Auto-detected from file type.
   */
  is_video?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Auto-generated from title. Edit only if needed.
   */
  slug: string;
  startAt: string;
  endAt?: string | null;
  location?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  image?: (number | null) | Media;
  status: 'draft' | 'published';
  featured?: boolean | null;
  /**
   * Link to the venue Organization record for this event
   */
  organization?: (number | null) | Organization;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  type: 'brewery' | 'pet_store' | 'gift_shop' | 'gallery' | 'cafe' | 'venue' | 'other';
  address?: string | null;
  neighborhood?: string | null;
  location?: string | null;
  notes?: string | null;
  city?: string | null;
  state?: string | null;
  country?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  placeId?: string | null;
  /**
   * Handle only, no @
   */
  instagram?: string | null;
  website?: string | null;
  email?: string | null;
  phone?: string | null;
  contactNotes?: string | null;
  contacts?:
    | {
        contactName?: string | null;
        role?: string | null;
        email?: string | null;
        phone?: string | null;
        preferredContactMethod?: ('email' | 'instagram_dm' | 'contact_form' | 'phone' | 'in_person') | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  dogFriendly?: boolean | null;
  hasEventSpace?: boolean | null;
  popUpHistory?: boolean | null;
  independentlyOwned?: boolean | null;
  rating?: number | null;
  fitScore?: ('top_tier' | 'strong' | 'worth_trying') | null;
  pinned?: boolean | null;
  fitNotes?: string | null;
  status:
    | 'researched'
    | 'contacted'
    | 'opened_email'
    | 'responded'
    | 'meeting_scheduled'
    | 'upcoming_event'
    | 'ongoing_relationship'
    | 'past_collaborator'
    | 'declined'
    | 'no_response';
  dateContacted?: string | null;
  contactMethod?: ('eblast' | 'personal_email' | 'instagram' | 'website_form' | 'other') | null;
  followUpDate?: string | null;
  responseNotes?: string | null;
  eventDate?: string | null;
  eventTerms?: string | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  jobs?: {
    docs?: (number | Job)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  first_name?: string | null;
  last_name?: string | null;
  email: string;
  notes?: string | null;
  phone?: string | null;
  address?: {
    street1?: string | null;
    street2?: string | null;
    city?: string | null;
    state?: string | null;
    zip?: string | null;
    country?: string | null;
  };
  company?: string | null;
  price?: number | null;
  /**
   * Client has consented to marketing emails
   */
  marketing_consent?: boolean | null;
  /**
   * Client has consented to portfolio display
   */
  portfolio_consent?: boolean | null;
  /**
   * Tags for Segmentation
   */
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  /**
   * Customer who commissioned this work
   */
  client: number | Client;
  /**
   * Link to a venue Organization for event/bulk orders
   */
  organization?: (number | null) | Organization;
  /**
   * Event this job was created at
   */
  event?: (number | null) | Event;
  /**
   * Street: 5-10 days to ship. Studio: 1-2 weeks to ship.
   */
  job_type?: ('street' | 'studio') | null;
  due_date?: string | null;
  urgency?: ('low' | 'medium' | 'high') | null;
  delivery_method?: ('pickup' | 'delivery' | 'other') | null;
  notes?: string | null;
  pinned?: boolean | null;
  /**
   * Pet information from intake form
   */
  pets: {
    name: string;
    sex?: ('male' | 'female' | 'unknown') | null;
    /**
     * e.g. 3 years, 6 months
     */
    age?: string | null;
    /**
     * Breed and markings
     */
    breed?: string | null;
    /**
     * Personality notes from intake form
     */
    personality?: string | null;
    /**
     * Pet's social media handles
     */
    social_media?: string | null;
    /**
     * Reference photos uploaded by client
     */
    pics?: (number | Media)[] | null;
    id?: string | null;
  }[];
  status:
    | 'inquiry'
    | 'intake_received'
    | 'in_progress'
    | 'awaiting_pics_or_payment'
    | 'ready_to_ship'
    | 'delivered'
    | 'portfolio_ready';
  /**
   * Auto-calculated: true if any pet has pics uploaded
   */
  pics_received?: boolean | null;
  payment_methods?:
    | {
        method?: ('website' | 'pos' | 'cash' | 'venmo' | 'zelle' | 'other') | null;
        amount?: number | null;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * cs_... — captured from /intake?session=... on submit
   */
  stripe_checkout_session_id?: string | null;
  /**
   * plink_... — which Payment Link the customer used
   */
  stripe_payment_link_id?: string | null;
  /**
   * pi_... — reconciliation key for refunds / disputes
   */
  stripe_payment_intent_id?: string | null;
  /**
   * cus_... — matches returning customers
   */
  stripe_customer_id?: string | null;
  /**
   * session.amount_total in smallest currency unit
   */
  stripe_amount_paid_cents?: number | null;
  /**
   * ISO currency code, lowercase (e.g. usd)
   */
  stripe_currency?: string | null;
  /**
   * session.payment_status at time of intake
   */
  stripe_payment_status?: ('paid' | 'unpaid' | 'no_payment_required') | null;
  /**
   * Total coupon savings applied to this session
   */
  stripe_amount_discount_cents?: number | null;
  /**
   * Tax collected by Stripe at checkout (session.total_details.amount_tax)
   */
  stripe_amount_tax_cents?: number | null;
  /**
   * Names of coupons or promo codes applied
   */
  stripe_discount_codes?:
    | {
        code?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mirrored from Stripe at checkout
   */
  shipping_address?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postal_code?: string | null;
    country?: string | null;
  };
  /**
   * How did you hear about us?
   */
  referral?: string | null;
  /**
   * Portfolio display settings - completed artwork for public showcase
   */
  portfolio?: {
    /**
     * Finished artwork images with flexible tagging
     */
    images?:
      | {
          image: number | Media;
          /**
           * Tag images to designate usage (can select multiple). Change tags to swap which is main/thumb without re-uploading.
           */
          image_tags?: ('main' | 'thumbnail' | 'alternate' | 'wip' | 'detail')[] | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Reference photos to display in portfolio (select from intake pics or upload altered versions)
     */
    reference_images?:
      | {
          /**
           * Original intake pic or edited version for portfolio display
           */
          image?: (number | null) | Media;
          /**
           * Uncheck if this is an altered/cropped version
           */
          is_original?: boolean | null;
          /**
           * Tag reference images for display context
           */
          reference_tags?: ('featured' | 'before' | 'cropped' | 'enhanced')[] | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Client testimonial or feedback
     */
    testimonial?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Only published items appear on public portfolio
     */
    portfolio_status?: ('hidden' | 'draft' | 'published') | null;
    /**
     * Highlight on homepage
     */
    featured?: boolean | null;
    /**
     * Categories (e.g., "dog", "cat", "watercolor")
     */
    portfolio_tags?:
      | {
          tag?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  pet_names?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-events".
 */
export interface IntakeEvent {
  id: number;
  session_id: string;
  event_type: 'field_progress' | 'validation_blocked' | 'submit_failed' | 'abandoned';
  form_snapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error_details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  stripe_session_id?: string | null;
  user_agent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'intake-events';
        value: number | IntakeEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  tags?: T;
  is_video?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startAt?: T;
  endAt?: T;
  location?: T;
  description?: T;
  image?: T;
  status?: T;
  featured?: T;
  organization?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  jobs?: T;
  first_name?: T;
  last_name?: T;
  email?: T;
  notes?: T;
  phone?: T;
  address?:
    | T
    | {
        street1?: T;
        street2?: T;
        city?: T;
        state?: T;
        zip?: T;
        country?: T;
      };
  company?: T;
  price?: T;
  marketing_consent?: T;
  portfolio_consent?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  client?: T;
  organization?: T;
  event?: T;
  job_type?: T;
  due_date?: T;
  urgency?: T;
  delivery_method?: T;
  notes?: T;
  pinned?: T;
  pets?:
    | T
    | {
        name?: T;
        sex?: T;
        age?: T;
        breed?: T;
        personality?: T;
        social_media?: T;
        pics?: T;
        id?: T;
      };
  status?: T;
  pics_received?: T;
  payment_methods?:
    | T
    | {
        method?: T;
        amount?: T;
        date?: T;
        id?: T;
      };
  stripe_checkout_session_id?: T;
  stripe_payment_link_id?: T;
  stripe_payment_intent_id?: T;
  stripe_customer_id?: T;
  stripe_amount_paid_cents?: T;
  stripe_currency?: T;
  stripe_payment_status?: T;
  stripe_amount_discount_cents?: T;
  stripe_amount_tax_cents?: T;
  stripe_discount_codes?:
    | T
    | {
        code?: T;
        id?: T;
      };
  shipping_address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postal_code?: T;
        country?: T;
      };
  referral?: T;
  portfolio?:
    | T
    | {
        images?:
          | T
          | {
              image?: T;
              image_tags?: T;
              id?: T;
            };
        reference_images?:
          | T
          | {
              image?: T;
              is_original?: T;
              reference_tags?: T;
              id?: T;
            };
        testimonial?: T;
        portfolio_status?: T;
        featured?: T;
        portfolio_tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
      };
  pet_names?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  address?: T;
  neighborhood?: T;
  location?: T;
  notes?: T;
  city?: T;
  state?: T;
  country?: T;
  latitude?: T;
  longitude?: T;
  placeId?: T;
  instagram?: T;
  website?: T;
  email?: T;
  phone?: T;
  contactNotes?: T;
  contacts?:
    | T
    | {
        contactName?: T;
        role?: T;
        email?: T;
        phone?: T;
        preferredContactMethod?: T;
        notes?: T;
        id?: T;
      };
  dogFriendly?: T;
  hasEventSpace?: T;
  popUpHistory?: T;
  independentlyOwned?: T;
  rating?: T;
  fitScore?: T;
  pinned?: T;
  fitNotes?: T;
  status?: T;
  dateContacted?: T;
  contactMethod?: T;
  followUpDate?: T;
  responseNotes?: T;
  eventDate?: T;
  eventTerms?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intake-events_select".
 */
export interface IntakeEventsSelect<T extends boolean = true> {
  session_id?: T;
  event_type?: T;
  form_snapshot?: T;
  error_details?: T;
  stripe_session_id?: T;
  user_agent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}